name: React Boilerplate CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run prettier
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier:check && prettier write
      - name: Run lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
